console.log("sample")


// <h1 class="viod" id="opp" name="xyz">subject name</h1>
//<p id="ari" class="ultra" name="abc">description</p>

// by tag name

let nnn=document.querySelector('p')
console.log(nnn)

let jkl=document.querySelector('h1')
console.log(jkl)

//by class name 

let rrr=document.querySelector('.ultra')
console.log(rrr)

let jjj=document.querySelector('.viod')
console.log(jjj)


// by id

let yyy=document.querySelector('#oop')
console.log(yyy)


let hhh=document.querySelector('#a12')
console.log(hhh)



// common

let lll = document.querySelector('h1[name="xyz"]')
console.log(lll)

